#!/usr/bin/env python3
"""Extract cursor bitmap data from Chromium .cur files into a C++ header.

Parses the 24-bit image from each .cur file (hand_grab.cur, hand_grabbing.cur)
and writes cursor_data.h in the Win32 windowing directory, with pre-extracted
pixel arrays + hotspots + BSD-3 attribution.

Usage (from libs/visage/tools/):
    python3 extract_cursor.py

Re-run if the source .cur files are updated.
"""

import struct
from pathlib import Path

HERE = Path(__file__).parent
CUR_DIR = HERE / "cursors"
OUT_PATH = HERE.parent / "visage_windowing" / "win32" / "cursor_data.h"


def parse_cur(path):
    """Parse a .cur file and return the 24-bit 32x32 image + hotspot + masks."""
    data = path.read_bytes()
    _, ctype, count = struct.unpack_from("<HHH", data, 0)
    if ctype != 2:
        raise RuntimeError(f"{path}: not a CUR file (type={ctype})")

    for i in range(count):
        entry_off = 6 + 16 * i
        w, h, _pal, _res, hx, hy, _size, off = struct.unpack_from(
            "<BBBBHHII", data, entry_off
        )
        w = 256 if w == 0 else w
        h = 256 if h == 0 else h
        bpp = struct.unpack_from("<H", data, off + 14)[0]
        if bpp == 24 and w == 32 and h == 32:
            bih_size = struct.unpack_from("<I", data, off)[0]
            image_start = off + bih_size
            row_bytes = ((w * bpp + 31) // 32) * 4
            color_size = row_bytes * h
            mask_row = ((w + 31) // 32) * 4
            mask_size = mask_row * h
            return {
                "width": w,
                "height": h,
                "hotspot_x": hx,
                "hotspot_y": hy,
                "bpp": bpp,
                "color": data[image_start : image_start + color_size],
                "mask": data[image_start + color_size : image_start + color_size + mask_size],
            }

    raise RuntimeError(f"{path}: no 24-bit 32x32 image found")


def emit_array(name, data):
    rows = []
    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        rows.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return (
        f"static const unsigned char {name}[{len(data)}] = {{\n"
        + "\n".join(rows)
        + "\n};"
    )


LICENSE_HEADER = """/* Copyright Vital Audio, LLC
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

/* Grab/Grabbing cursor bitmap data.
 *
 * Extracted from Chromium's open-source cursor assets:
 *   ui/resources/cursors/hand_grab.cur
 *   ui/resources/cursors/hand_grabbing.cur
 *
 * Copyright (c) The Chromium Authors. All rights reserved.
 * Licensed under BSD-3-Clause:
 *
 *   Redistribution and use in source and binary forms, with or without
 *   modification, are permitted provided that the following conditions are
 *   met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Google LLC nor the names of its contributors may
 *       be used to endorse or promote products derived from this software
 *       without specific prior written permission.
 *
 * This file is auto-generated by tools/extract_cursor.py. Do not edit by hand;
 * re-run the extraction script to regenerate.
 */

#pragma once
"""


def main():
    grab = parse_cur(CUR_DIR / "hand_grab.cur")
    grabbing = parse_cur(CUR_DIR / "hand_grabbing.cur")

    parts = [
        LICENSE_HEADER,
        "",
        "namespace visage {",
        "namespace cursor_data {",
        "",
        "struct EmbeddedCursor {",
        "  int width;",
        "  int height;",
        "  int hotspot_x;",
        "  int hotspot_y;",
        "  int bits_per_pixel;",
        "  const unsigned char* color_bits;",
        "  int color_size;",
        "  const unsigned char* and_mask;",
        "  int mask_size;",
        "};",
        "",
        "// hand_grab (open hand)",
        emit_array("kGrabColorBits", grab["color"]),
        "",
        emit_array("kGrabAndMask", grab["mask"]),
        "",
        "inline constexpr EmbeddedCursor kGrab = {",
        f"  {grab['width']}, {grab['height']},  // width, height",
        f"  {grab['hotspot_x']}, {grab['hotspot_y']},  // hotspot",
        f"  {grab['bpp']},  // bits_per_pixel",
        f"  kGrabColorBits, sizeof(kGrabColorBits),",
        f"  kGrabAndMask, sizeof(kGrabAndMask),",
        "};",
        "",
        "// hand_grabbing (closed fist)",
        emit_array("kGrabbingColorBits", grabbing["color"]),
        "",
        emit_array("kGrabbingAndMask", grabbing["mask"]),
        "",
        "inline constexpr EmbeddedCursor kGrabbing = {",
        f"  {grabbing['width']}, {grabbing['height']},  // width, height",
        f"  {grabbing['hotspot_x']}, {grabbing['hotspot_y']},  // hotspot",
        f"  {grabbing['bpp']},  // bits_per_pixel",
        f"  kGrabbingColorBits, sizeof(kGrabbingColorBits),",
        f"  kGrabbingAndMask, sizeof(kGrabbingAndMask),",
        "};",
        "",
        "}  // namespace cursor_data",
        "}  // namespace visage",
        "",
    ]

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(parts))

    print(f"Wrote {OUT_PATH}")
    for name, c in [("kGrab", grab), ("kGrabbing", grabbing)]:
        print(
            f"  {name}: {c['width']}x{c['height']} @{c['bpp']}bpp, "
            f"hotspot=({c['hotspot_x']},{c['hotspot_y']})"
        )
        print(f"    color: {len(c['color'])} bytes, mask: {len(c['mask'])} bytes")


if __name__ == "__main__":
    main()
